packages:
  - .

allowBuilds:
  bufferutil: true
  sharp: true
  utf-8-validate: true

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - better-sqlite3
  - bufferutil
  - sharp
  - utf-8-validate
